### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pillborn**

### CODE REVIEW

**Comment by Phytolizer** [comment]
Who is this? Also it doesn't run well on any OS because it isn't finished

**Comment by Pillborn** [comment]
Have you seen hacktpberfest. I'm helping your project to get s teeshirt

**Comment by WestonReed** [comment]
This app wasn't well developed. Everyone went their own way and we ended up with this monstrosity.

**Comment by AllenCompSci** [comment]
They are doing the "Hacktoberfest 2017" via Digital Oceans. Check it out.  https://hacktoberfest.digitalocean.com/

They modified as part of the pull requests minimum change.

**Pull request merged**
